default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

staging:
  <<: *default

static:
  <<: *default

production:
  <<: *default
